/**
 * Unified error codes per D16.
 * Format: DOMAIN_REASON
 */
export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  // Profile
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_ALREADY_EXISTS: 'PROFILE_ALREADY_EXISTS',

  // Asset
  ASSET_INVALID_FORMAT: 'ASSET_INVALID_FORMAT',
  ASSET_TOO_LARGE: 'ASSET_TOO_LARGE',
  ASSET_DURATION_EXCEEDED: 'ASSET_DURATION_EXCEEDED',
  ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
  ASSET_UPLOAD_FAILED: 'ASSET_UPLOAD_FAILED',

  // Task
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_ALREADY_RUNNING: 'TASK_ALREADY_RUNNING',
  TASK_CANNOT_CANCEL: 'TASK_CANNOT_CANCEL',

  // Credit
  CREDIT_INSUFFICIENT_BALANCE: 'CREDIT_INSUFFICIENT_BALANCE',
  CREDIT_HOLD_FAILED: 'CREDIT_HOLD_FAILED',
  CREDIT_ALREADY_SETTLED: 'CREDIT_ALREADY_SETTLED',

  // Risk
  RISK_PRECHECK_BLOCKED: 'RISK_PRECHECK_BLOCKED',
  RISK_CONTENT_BLOCKED: 'RISK_CONTENT_BLOCKED',
  RISK_MANUAL_REVIEW_REQUIRED: 'RISK_MANUAL_REVIEW_REQUIRED',

  // Consent
  CONSENT_NOT_CONFIRMED: 'CONSENT_NOT_CONFIRMED',
  CONSENT_EXPIRED: 'CONSENT_EXPIRED',

  // System
  SYSTEM_INTERNAL_ERROR: 'SYSTEM_INTERNAL_ERROR',
  SYSTEM_SERVICE_UNAVAILABLE: 'SYSTEM_SERVICE_UNAVAILABLE',
  SYSTEM_RATE_LIMITED: 'SYSTEM_RATE_LIMITED',
} as const;
